### ISSUE TITLE
我无法使用密码"abc"打开output.pdf

### ISSUE THREAD

**Issue by Jun1172** [AndreRenaud/PDFGen#106]
您好
我使用origin/encryption生成了output.pdf，但是无法打开
[uint8_t password[] = {""'a', 'b', 'c'""};
pdf_set_encryption(pdf, 0, password, sizeof(password), NULL,
                       0); // password, sizeof(password));](url)

上面代码不是真实密码么？

**Comment by AndreRenaud** [comment]
Sorry I cannot read chinese.
Unfortunately, the code does not work, it is just an experiment. I haven't finished it yet and am not working on it at the moment.

抱歉我看不懂中文。
不幸的是，代码不起作用，它只是一个实验。 我还没有完成它，目前没有工作。

**Comment by Jun1172** [comment]
Thanks   (●'◡'●)

**Comment by AndreRenaud** [comment]
I'll close this issue for now - there is an existing issue #92 used to track encryption support. Please comment on that one if you would like to progress this further. Thanks.
