### ISSUE TITLE
Minor gcc warning in pdfgen.c

### ISSUE THREAD

**Issue by ctp52** [AndreRenaud/PDFGen#134]
pdfgen.c: In function ‘find_word_break’:
pdfgen.c:1822:42: warning: comparison is always false due to limited range of data type [-Wtype-limits]
 1822 |     while (string && *string && (*string < 0 || !isspace(*string)))

---

static const char *find_word_break(const char *string)
{
    /* Skip over the actual word */
    while (string && *string && (*string < 0 || !isspace(*string)))
        string++;

    return string;
}

---

While statement should be:

    while (string && *string && (*string <= 0 || !isspace(*string)))

**Comment by AndreRenaud** [comment]
`<= 0` is already covered by *string. This is a weirdly worded line which works differently when you've got signed & unsigned char by default (I think ARM has it unsigned, and x86 has it signed - https://en.cppreference.com/w/cpp/language/types)

So the upshot is I think this is broken on unsigned char (ARM), but the change you're proposing won't fix it. It should be something like:

`while (string && *string && (*string & 0x80 == 0x80 || isspace(*string)))`

Although perhaps the whole <= 0 thing can go. This is utf-8 encoding related. I'll give it some thought and see if I can work out the best replacement.

**Comment by AndreRenaud** [comment]
Yes. I cannot for the life of me work out what I was intending to do with that original line. I think it can become:
`while (string && isspace(*string))`

**Comment by ctp52** [comment]
I did not include details of the environment used in this compile because I use Debian 12 on both ARM64 and AMD64 and I "think" the error was reported on both. I have deleted the relevant directory on AMD64 so I can not confirm it happened on both.

>gcc --version
gcc (Debian 12.2.0-14) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.

on both machines.
