### ISSUE TITLE
Generated PDF Comes Broken

### ISSUE THREAD

**Issue by ffreality** [AndreRenaud/PDFGen#135]
I am working on pdf writer plugin for Unreal Engine 5.
I have plugins with PDFium and LibHaru but they have lots of problem so I am looking additional solutions.

(LibHaru doesn't work with mobile and suggested callback functions for saving PDFs on PDFium doesn't work with image inserted PDFs. They say we need to append our file with a loop but there is no sample or documentation about it.)

I included pdfgen.c and pdfgen.h from your master repo and write these codes as sample.

```
void UFF_PDFGENBPLibrary::PDFGen_Create_Doc(UPdfGenDoc*& Out_PDF, FString In_Author, FString In_Creator, FDateTime In_Date, FString In_Producer, FString In_Subject, FString In_Title, FVector2D In_Size, FString Path)
{
	/*
	const pdf_info PDF_Info = 
	{
		*TCHAR_TO_UTF8(*In_Creator),
		*TCHAR_TO_UTF8(*In_Producer),
		*TCHAR_TO_UTF8(*In_Title),
		*TCHAR_TO_UTF8(*In_Author),
		*TCHAR_TO_UTF8(*In_Subject),
		*TCHAR_TO_UTF8(*In_Date.ToString())
	};
	*/

	struct pdf_info info = {
		"My software",
		"My software",
		"My document",
		"My name",
		"My subject",
		"Today"
	};

	pdf_doc* Document = pdf_create(PDF_A4_WIDTH, PDF_A4_HEIGHT, &info);

	pdf_add_text(Document, NULL, "This is text", 12, 50, 20, PDF_BLACK);
	pdf_add_line(Document, NULL, 50, 24, 150, 24, 3, PDF_BLACK);
	pdf_save(Document, TCHAR_TO_UTF8(*Path));
	pdf_destroy(Document);
}
```

first info structure gets its values from argument (inputs exposed to Unreal's blueprint system. So, we can change them without returning code even in runtime. FString is equal to const char*) but generated PDF stucked at %45 when I want to open it with chrome.
So, I commented it out and used second struct. I got same result.

Is there any suggestion for that ?
Also do you have a plan to update PDF system to 1.7 ?

This is generated PDF
[sample_pdfgen.pdf](https://github.com/AndreRenaud/PDFGen/files/12210239/sample_pdfgen.pdf)

**Comment by AndreRenaud** [comment]
You need to add a new page before you can start adding items, can you try this instead?

```
void UFF_PDFGENBPLibrary::PDFGen_Create_Doc(UPdfGenDoc*& Out_PDF, FString In_Author, FString In_Creator, FDateTime In_Date, FString In_Producer, FString In_Subject, FString In_Title, FVector2D In_Size, FString Path)
{
	/*
	const pdf_info PDF_Info = 
	{
		*TCHAR_TO_UTF8(*In_Creator),
		*TCHAR_TO_UTF8(*In_Producer),
		*TCHAR_TO_UTF8(*In_Title),
		*TCHAR_TO_UTF8(*In_Author),
		*TCHAR_TO_UTF8(*In_Subject),
		*TCHAR_TO_UTF8(*In_Date.ToString())
	};
	*/

	struct pdf_info info = {
		"My software",
		"My software",
		"My document",
		"My name",
		"My subject",
		"Today"
	};

	pdf_doc* Document = pdf_create(PDF_A4_WIDTH, PDF_A4_HEIGHT, &info);

        pdf_append_page(pdf);
	pdf_add_text(Document, NULL, "This is text", 12, 50, 20, PDF_BLACK);
	pdf_add_line(Document, NULL, 50, 24, 150, 24, 3, PDF_BLACK);
	pdf_save(Document, TCHAR_TO_UTF8(*Path));
	pdf_destroy(Document);
}
```

At this stage, I don't have any plans to move to 1.7. PDFGen is designed to be self-contained, and simple. If you need complex functionality, then it's probably not the library for the task. Is there a specific feature in 1.7 that you need?

**Comment by AndreRenaud** [comment]
1. For the PDF 1.7, even though the current version is pretty old, PDF is an archival format, so they're not so much obsolete as unchanging. Unless there is a specific tool that is breaking with the current output, I don't think I'll change it. You mentioned some tools that don't support < 1.5 - can you tell me which tools & how they break? I could look into that.

2. Yeah, the append page vs. create is slightly confusing. It would be possible to create a helper function that returned you a given page index (ie: `pdf_get_page(pdf_doc, 2)` to get the second page). Right now it's the callers responsibility to remember them.

3. I'm not entirely sure I understand what you mean with the strcpy comment you've made. If you're happy with your solution, then we can probably leave it there. If you'd like some feedback, please post the code you ended up with.

**Comment by AndreRenaud** [comment]
Would this kind of functionality be sufficient for the page support?

https://github.com/AndreRenaud/PDFGen/pull/136

**Comment by ffreality** [comment]
Yes, that get page function is perfect ! but right now I can save and get pages. I just need to expose `add and delete page` functionalities.

This is my repo and its section about strcpy
https://github.com/FF-Plugins-Docs/FF_PDFGEN/blob/main/Source/FF_PDFGEN/Private/FF_PDFGENBPLibrary.cpp#L26

For PDF 1.3, one of them is Atlassian JIRA.
But you are right even if I have some problems about 1.3, I can convert it to newer ones.
