### ISSUE TITLE
The pdf_add_text_wrap method does not work for me

### ISSUE THREAD

**Issue by bellongart** [AndreRenaud/PDFGen#143]
I have tried using the pdf_add_text_wrapp method, but without success. I don't know if I'm doing something wrong, but I can't get it to work. I have used the fuzz-text.c example but it doesn't even show me the text in the document I generate.

**Comment by AndreRenaud** [comment]
Could you past in your code here for me to check?

The following code should work:
```c
#include <stdio.h>
#include "pdfgen.h"

int main(void) {
   
struct pdf_doc *pdf = pdf_create(PDF_A4_WIDTH, PDF_A4_HEIGHT, NULL);
    pdf_set_font(pdf, "Times-Roman");
    pdf_append_page(pdf);
    pdf_add_text_wrap(pdf, NULL, "This is a long line of text", 24, 50, PDF_A4_HEIGHT - 50, 0, PDF_BLACK, 40, PDF_ALIGN_CENTER, NULL);
    pdf_save(pdf, "output.pdf");
    pdf_destroy(pdf);
    return 0;
}
```
[output.pdf](https://github.com/AndreRenaud/PDFGen/files/12898185/output.pdf)

**Comment by AndreRenaud** [comment]
I should probably add - the fuzz tests are not really good example of how to use the code. They're the minimum amount of code I needed to write to get the fuzzer tied into each function. The Readme & `main.c` are better places to look.

**Comment by bellongart** [comment]
I think I already discovered the problem. When I use a font other than those used or can be used according to the documentation, it doesn't show anything in the generated document, but when I change the font to a valid one, like 'Times-Roman', it works perfectly.

**Comment by AndreRenaud** [comment]
Ah, yes. Unfortunately PDFGen doesn't support arbitrary fonts at the moment, just those that are built into the PDF standard. So you're limited to those options.

I'll close this issue, but feel free to open a new one if you have any other questions.
