### ISSUE TITLE
Bisotun: A wrapper library around PDFGen

### ISSUE THREAD

**Issue by LinArcX** [AndreRenaud/PDFGen#150]
I'm very excited to share with anyone interested in PDFGen, which I made a wrapper library around PDFGen to writing documents more simple and a little bit more high-level:

https://github.com/LinArcX/bisotun

Actually, I'm using it mainly to create my resume, but you can generate books and other kind of documents with it.

Thanks again Andre for your great library.

**Comment by AndreRenaud** [comment]
Thanks for letting me know. I hope you're finding it useful.

I still intend to come back to TTF font support at some point, but unfortunately it's not in my schedule at the moment.
