### ISSUE TITLE
WinAnsiEncoding

### ISSUE THREAD

**Issue by adalbermirom** [AndreRenaud/PDFGen#2]
Hey, bro.
you have an excellent library
I'm using it.
I made some changes to include winansiencoding. If you want to take a look, follow the code:
**Line: 650**
```
case OBJ_font:
        /*
        fprintf(fp, "<<\r\n"
                "  /Type /Font\r\n"
                "  /Subtype /Type1\r\n"
                "  /BaseFont /%s\r\n"
                ">>\r\n", object->font.name);
        */
        fprintf(fp, "<<\r\n"   /*WinAnsiEncoding*/
         "  /Type /Font\r\n"
         "  /BaseFont /%s\r\n"
         "  /Subtype /Type1\r\n"
         "  /Encoding /WinAnsiEncoding\r\n"
         ">>\r\n", object->font.name);
        break;
```
some Utf8 to WinAnsiEncoding:
**Line: 897**

```
#ifndef pdf_UCHAR 
#define pdf_UCHAR(c) (unsigned char)c
#endif

int pdf_add_text(struct pdf_doc *pdf, struct pdf_object *page,
                 const char *text, int size, int xoff, int yoff,
                 uint32_t colour)
{
    int i, ret;
    int len = text ? strlen(text) : 0;
    struct dstr str = {0, 0, 0};

    /* Don't bother adding empty/null strings */
    if (!len)
        return 0;

    dstr_append(&str, "BT ");
    dstr_printf(&str, "%d %d TD ", xoff, yoff);
    dstr_printf(&str, "/F%d %d Tf ",
                pdf->current_font->font.index, size);
    dstr_printf(&str, "%f %f %f rg ",
                PDF_RGB_R(colour), PDF_RGB_G(colour), PDF_RGB_B(colour));
    dstr_append(&str, "(");

    /* Escape magic characters properly */
    for (i = 0; i < len; i++) { 
        if (strchr("()\\", text[i])) {
            char buf[3];
            /* Escape some characters */
            buf[0] = '\\';
            buf[1] = text[i];
            buf[2] = '\0';
            dstr_append(&str, buf);
        } else if (strrchr("\n\r\t\b\f", text[i])) {
            /* Skip over these characters */
            ;
        } else if( pdf_UCHAR(text[i]) == 226){
			char buf[5];
			buf[0] = '\\';
			buf[1] = '2';
			buf[2] = '0';
			buf[3] = '0';
			buf[4] = '\0';/* \200 : euro symbol*/
            dstr_append(&str, buf);
            i++; i++; /*jump two unused characters*/
        }else if(  pdf_UCHAR(text[i]) == 195){
		   char buf[2];
		   buf[0] =  pdf_UCHAR(text[i+1]) + 64;
		   buf[1] = '\0';
		   dstr_append(&str, buf);	
		   i++;   			
		} else if(  pdf_UCHAR(text[i]) == 194){
			/*skip this*/
		}else {
            char buf[2];
            buf[0] = text[i];
            buf[1] = '\0';
            dstr_append(&str, buf);
        }
        
    }
    dstr_append(&str, ") Tj ");
    dstr_append(&str, "ET");
    /*printf("\n\n---<<%s>>\n\n", str.data);*/
    ret = pdf_add_stream(pdf, page, str.data);
    dstr_free(&str);
    return ret;
}
```

Sorry for my English, I'm Brazilian. I'm not an expert on C programming, and if you can perfect or fix it, I'm happy.

**Comment by AndreRenaud** [comment]
Hey. Thanks for reporting this. PDFGen really doesn't handle non-ascii characters at all at the moment unfortunately. I don't think supporting the full utf-8 encoding is likely, but I imagine it should be possible to get it going with ISO-8859-1.

I'm not sure I quite understand the kind of behaviour you're trying to get - can you tell me the characters you're wanting to display?
I've fiddled with something like:
    pdf_add_text(pdf, NULL, "UTF-8 encoded characters: €ÜŽžŤťČčŠšÁáüöäÄÜÖß", 10, 50, 15, PDF_RGB(0, 0, 0));
This is certainly broken at the moment. Is that what you had in mind? If that's it, what I think is necessary is to convert a UTF-8 encoded input string into ISO-8859-1, perhaps discarding (or erroring out) on characters that can't be done this way.

Let me know if this is the kind of thing you're after, and we'll see what can be done.

Thanks

**Comment by adalbermirom** [comment]
Thanks for answering.

Exactly this, not the ISO-8859-1 but the cp1252:
`<<
  / Type / Font
  / BaseFont / Times-Roman
  / Subtype / Type1
  / Encoding / WinAnsiEncoding
>>`

I tried to do this in this piece of code:

`else if (pdf_UCHAR (text [i]) == 226) {
char buf [5];
buf [0] = '\\';
buf [1] = '2';
buf [2] = '0';
buf [3] = '0';
buf [4] = '\ 0'; / * \ 200: euro symbol * /
        dstr_append (& str, buf);
        i ++; i ++; / * jump two unused characters * /
    } else if (pdf_UCHAR (text [i]) == 195) {
char buf [2];
buf [0] = pdf_UCHAR (text [i + 1]) + 64;
buf [1] = '\ 0';
dstr_append (& str, buf);
i ++;
}`

And it seems to have given some result, but not every utf8 character is supported, unfortunately.

**Comment by AndreRenaud** [comment]
I've just pushed through a change that allows some UTF-8 characters to be converted to their CP1252 equivalents. It's very rudimentary, but hopefully it'll be enough. Can you retry from HEAD and confirm if the issue is resolved?

**Comment by AndreRenaud** [comment]
I'm going to resolve this since I think it's fixed. Feel free to send me a message if there is still a problem.
