### ISSUE TITLE
PDF size

### ISSUE THREAD

**Issue by nomancyclewala** [AndreRenaud/PDFGen#25]
I am using this library to dynamically create upto 50 Pages which generates a file with a size of 5.5MB. Is there a way to control the size of the output file ? or any other ways to reduce the dpi of the pdf ?

**Comment by AndreRenaud** [comment]
Hi. Are you able to send through the PDF, and possible an example of how you're generating it?
In general PDFGen isn't designed for concise output. There is no compression, or attempts to minimise things. If you're able to send through an example of things there might me some small wins that we could use to reduce things.

**Comment by nomancyclewala** [comment]
Code : 
`#include "pdfgen.h"
#include "string.h"
#include "stdlib.h"



void add_column (int,int,char *);
void add_data_page(int);


uint8_t datapoints[10000][30];
char temp_buffer[25];

	int date,month,year,hour,minute,second,max_temp,min_temp;
	float temperature;


char temp_buf[50];
int text_size = 7;

struct pdf_doc *pdf_ptr = NULL;

int main(void) {
    struct pdf_info info = {
        .creator = "My software",
        .producer = "My software",
        .title = "My document",
        .author = "My name",
        .subject = "My subject",
        .date = "Today"
    };
	
	
	
	
	
	
	
	
    struct pdf_doc *pdf = pdf_create(PDF_A4_WIDTH, PDF_A4_HEIGHT, &info);
	
	pdf_ptr = pdf;
    
	pdf_set_font(pdf, "Times-Roman");
    pdf_append_page(pdf);
    pdf_add_text(pdf, NULL, "TDL", 32 , 480 , 800 , PDF_BLUE);
    pdf_add_text(pdf,NULL,"Pccube Softtech",16,460,780,PDF_BLUE);
    pdf_add_text(pdf,NULL,"Data Report",38,120,760,PDF_BLACK);
	pdf_add_jpeg(pdf,NULL,50,750,50,50,"symbol.jpeg");
    pdf_add_text(pdf,NULL,"File Created Date : 17/08/2019 11:11:30",14,50,725,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Note : All times are based on GMT and 24 Hour  Format [DD/MM/YYYY HH:MM:SS]",14,50,710,PDF_RED);
    pdf_add_text(pdf,NULL,"Device Information",16,50,675,PDF_BLACK);
    pdf_add_line(pdf, NULL, 50 , 670 , 580 , 670, 2, PDF_BLACK);
	
	
    pdf_add_circle(pdf, NULL, 60, 654,2,1 ,PDF_BLACK,PDF_BLACK);
	pdf_add_text(pdf,NULL,"Serial Number",13,70,650,PDF_BLACK);
    pdf_add_text(pdf,NULL,"M31EBBD",13,300,650,PDF_BLACK);

	pdf_add_circle(pdf, NULL, 60, 639,2,1 ,PDF_BLACK,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Device Description : ",13,70,635,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Temperature Logger V2",13,300,635,PDF_BLACK);

    pdf_add_circle(pdf, NULL, 60, 624,2,1 ,PDF_BLACK,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Configuration Date: ",13,70,620,PDF_BLACK);
    pdf_add_text(pdf,NULL,"10/8/2019 11:11:35",13,300,620,PDF_BLACK);

    pdf_add_circle(pdf, NULL, 60, 609,2,1 ,PDF_BLACK,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Start Delay: ",13,70,605,PDF_BLACK);
    pdf_add_text(pdf,NULL,"10 Minute",13,300,605,PDF_BLACK);

    pdf_add_circle(pdf, NULL, 60, 594,2,1 ,PDF_BLACK,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Logging Interval: ",13,70,590,PDF_BLACK);
    pdf_add_text(pdf,NULL,"30 Minute",13,300,590,PDF_BLACK);

    pdf_add_circle(pdf, NULL, 60, 579,2,1 ,PDF_BLACK,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Absolute Temperature Range: ",13,70,575,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Maximum : 85 Degree C    Minimum : -40 Degree C",13,300,575,PDF_BLACK);

    pdf_add_circle(pdf, NULL, 60, 564,2,1 ,PDF_BLACK,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Configured Temperature Range: ",13,70,560,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Maximum : 85 Degree C    Minimum : -40 Degree C",13,300,560,PDF_BLACK);

    pdf_add_circle(pdf, NULL, 60, 549,2,1 ,PDF_BLACK,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Memory Usage: ",13,70,545,PDF_BLACK);
    pdf_add_text(pdf,NULL,"75%",13,300,545,PDF_BLACK);

    pdf_add_circle(pdf, NULL, 60, 534,2,1 ,PDF_BLACK,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Data Points: [Total Log entries] ",13,70,530,PDF_BLACK);
    pdf_add_text(pdf,NULL,"30000",13,300,530,PDF_BLACK);



    pdf_add_text(pdf,NULL,"Logging Summary",16,50,480,PDF_BLACK);
    pdf_add_line(pdf, NULL, 50 , 475 , 580 , 475, 2, PDF_BLACK);

    pdf_add_text(pdf,NULL,"Highest Temperature : ",12,60,450,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Lowest Temperature : ",12,60,430,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Average Temperature :",12,60,410,PDF_BLACK);

    pdf_add_text(pdf,NULL,"+41.9 °C",12,200,450,PDF_BLACK);
    pdf_add_text(pdf,NULL,"-23.5 °C",12,200,430,PDF_BLACK);
    pdf_add_text(pdf,NULL,"+15.4 °C",12,200,410,PDF_BLACK);



    pdf_add_text(pdf,NULL,"Start Time : ",12,350,450,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Stop Time : ",12,350,430,PDF_BLACK);
    pdf_add_text(pdf,NULL,"Elapsed Time : ",12,350,410,PDF_BLACK);

    pdf_add_text(pdf,NULL,"10/08/2019 11:11:30",12,440,450,PDF_BLACK);
    pdf_add_text(pdf,NULL,"17/08/2019 11:11:30",12,440,430,PDF_BLACK);
    pdf_add_text(pdf,NULL,"10D 0H 0M 00S",12,440,410,PDF_BLACK);




    pdf_add_text(pdf,NULL,"Temperature[°C]",18,40,350,PDF_BLACK);

	pdf_add_line(pdf, NULL, 50 , 300 , 550 , 300, 2, PDF_BLACK);
	pdf_add_line(pdf, NULL, 50 , 300 , 50 , 40, 2, PDF_BLACK);
    pdf_add_line(pdf, NULL, 50 , 40 , 550 , 40, 2, PDF_BLACK);
	pdf_add_line(pdf, NULL, 550 , 300 , 550 , 40, 2, PDF_BLACK);

	for(int i=50;i<550;i++)
	{
		for(int j=0;j<2;j++)
		{
	      pdf_add_circle(pdf, NULL, i, (    ((i+j)/2) > 50 ? ((i+j)/2) : 50),1,1 ,PDF_BLACK,PDF_BLACK);
		}
	}


	pdf_add_text(pdf,NULL,"Date / Time",13,265,20,PDF_BLACK);

	pdf_add_line(pdf, NULL, 10 , 10 , 590 , 10, 1, PDF_BLACK);

    pdf_add_text(pdf,NULL,"Page 1",12,550,15,PDF_BLACK);


    //pdf_append_page(pdf);


	date = 11;
	month = 8;
	year = 2019;
	hour = 16;
	minute = 42;
	second = 25;
	temperature = 32.5;
	max_temp = 45;
	min_temp = 15;
	
	
	int data_points;
	
	printf("Enter total Data Points : ");
	scanf("%d",&data_points);
	
	//int data_points = 32000;
	int pages = (data_points / 500) + 1;
	printf("Total Pages to be generated : %d",pages);
	

	for(int i=2;i<pages+2;i++)
	{
		add_data_page(i);
	}

    pdf_save(pdf, "output.pdf");
    pdf_destroy(pdf);
    return 0;
}







void add_data_page(int page_number)
{
	
	pdf_append_page(pdf_ptr);

	
	pdf_add_line(pdf_ptr, NULL, 10 , 800 , 590 , 800, 2, PDF_BLACK);
	pdf_add_text(pdf_ptr,NULL,"SN : ",11,20,810,PDF_BLACK);
    pdf_add_text(pdf_ptr,NULL,"M31EBBD",11,45,810,PDF_BLACK);
    
    pdf_add_text(pdf_ptr,NULL,"Variant : ",11,130,810,PDF_BLACK);
    pdf_add_text(pdf_ptr,NULL,"Single Use",11,175,810,PDF_BLACK);

	pdf_add_text(pdf_ptr,NULL,"Start Time : ",11,260,810,PDF_BLACK);
    pdf_add_text(pdf_ptr,NULL,"10/08/2019 11:11:30",11,315,810,PDF_BLACK);

	pdf_add_text(pdf_ptr,NULL,"Stop Time : ",11,440,810,PDF_BLACK);
    pdf_add_text(pdf_ptr,NULL,"17/08/2019 11:11:30",11,495,810,PDF_BLACK);



	pdf_add_line(pdf_ptr, NULL, 25 , 770 , 560 , 770, 1, PDF_BLACK);
	
	
	
	
	add_column(20,740,NULL);
	add_column(130,740,NULL);
	add_column(240,740,NULL);
	add_column(350,740,NULL);
	add_column(460,740,NULL);
	
	
	pdf_add_line(pdf_ptr, NULL, 25 , 750 , 560 , 750, 1, PDF_BLACK);

	pdf_add_line(pdf_ptr, NULL, 10 , 10 , 590 , 10, 1, PDF_BLACK);

	char buf[10];
	sprintf(buf,"Page %d",page_number);
    pdf_add_text(pdf_ptr,NULL,buf,12,550,15,PDF_BLACK);



}



void add_column (int x_axis , int y_axis , char * databuffer)

{
	
	pdf_add_line(pdf_ptr, NULL, x_axis+100 , y_axis + 30 , x_axis+100 , 50, 1, PDF_BLACK);
    pdf_add_text(pdf_ptr,NULL,"Date  Time  °C",11, x_axis+10, y_axis+15,PDF_BLACK);

	
	
	for(int i=0;	i< 100 ; i++)
	{
		sprintf(temp_buf," %d/%d/%d   %d:%d:%d  %.3f°C",date,month,year,hour,minute,second,temperature);
		pdf_add_text(pdf_ptr,NULL,temp_buf,text_size,x_axis,y_axis, temperature > max_temp ? PDF_RED : PDF_BLACK);
		y_axis -=7;
		
	}
}`



Generated PDF : 
[output.pdf](https://github.com/AndreRenaud/PDFGen/files/3553956/output.pdf)


I will be generating this pdf directly in a 4MB NOR flash. thats why i want to reduce the file size. I am also trying to make this library work on an MCU.

**Comment by AndreRenaud** [comment]
I think the simplest win would be for PDFGen to cache the current display state, and only output it when things have changed. This *should* mean that each text item won't repeat the colour, transparency etc... It won't be a massive gain, but it will be something. I'm a bit busy for the next few days, but I'll try and get something out within the week.
I'll also look at just making the output data a little less readable by removing some of the whitespace & jamming things together. It won't affect the display of the PDF, and I doubt many people are opening up the PDFs to inspect the raw details anyway - that was mostly just for my own benefit when I started.

**Comment by nomancyclewala** [comment]
> I think the simplest win would be for PDFGen to cache the current display state, and only output it when things have changed. This _should_ mean that each text item won't repeat the colour, transparency etc... It won't be a massive gain, but it will be something. I'm a bit busy for the next few days, but I'll try and get something out within the week.
> I'll also look at just making the output data a little less readable by removing some of the whitespace & jamming things together. It won't affect the display of the PDF, and I doubt many people are opening up the PDFs to inspect the raw details anyway - that was mostly just for my own benefit when I started.

your library has helped me alot , it has everything i needed to create the format of the pdf that i wanted to create. i was surprised myself that i made that kind of PDF with just a c program. And you might have seen my pdf that i generated. only first page is different and the rest has same format. 

Btw i have another idea , will it be possible for this library to _edit an existing PDF_ ? this way i could make a smaller format pdf on a pc and then just fill in the details according to the dynamic data.

**Comment by AndreRenaud** [comment]
Unfortunately parsing PDFs is quite different to creating them. A while ago I did have a look at creating something that would break a PDF down into the various objects and just save their raw contents into the same structure that PDFGen is using, but it started to get very complex, and I wasn't very happy with the results, so I never finished it. I agree that modifying templates would be nicer than creating things from scratch, but unfortunately I do not have any code for that at the moment.

**Comment by AndreRenaud** [comment]
Can you try the code that is available on the 'reduce-output-size' branch?

https://github.com/AndreRenaud/PDFGen/tree/reduce-output-size
If your file consists of a lot of sequential text objects that all have the same font, size & colour, this should reduce the output significantly.

**Comment by nomancyclewala** [comment]
> Can you try the code that is available on the 'reduce-output-size' branch?
> 
> https://github.com/AndreRenaud/PDFGen/tree/reduce-output-size
> If your file consists of a lot of sequential text objects that all have the same font, size & colour, this should reduce the output significantly.

i will try this and report back asap. thanks

**Comment by AndreRenaud** [comment]
If you're trying to save it to NOR on an MCU, you'll still need to have a pretty similar amount of RAM available. The PDF objects stored in RAM are pretty close in size to what is required to write it out. So unless your MCU has a lot of RAM, you'll probably still have issues on that front. There isn't much I can do about that I'm afraid. PDFs aren't designed for streaming output (because of the XRef section), so there is no good method of freeing up objects prior to the final write.

**Comment by nomancyclewala** [comment]
> If you're trying to save it to NOR on an MCU, you'll still need to have a pretty similar amount of RAM available. The PDF objects stored in RAM are pretty close in size to what is required to write it out. So unless your MCU has a lot of RAM, you'll probably still have issues on that front. There isn't much I can do about that I'm afraid. PDFs aren't designed for streaming output (because of the XRef section), so there is no good method of freeing up objects prior to the final write.

Thanks for the heads up , i will surely look into that.

Btw , There was some chinese guy who has modified your library to work on 80KB of RAM. 
check this out : https://github.com/Jun1172/stm32_pdflib_msc_storage/tree/master/Drivers/pdflib

but his version has become very basic so i will try to get some balance between ram usage and functionality.

**Comment by AndreRenaud** [comment]
Thanks for that link. I'm not sure if that library is based on PDFGen or not. The source code doesn't appear to have much similarity. It looks more like an independent implementation.

**Comment by AndreRenaud** [comment]
This issue appears to have gone dormant. If nobody still really needs this functionality, I'll probably close it soon.

**Comment by AndreRenaud** [comment]
Closing as it doesn't look like this feature is still required. Will re-open if necessary.
