### ISSUE TITLE
Visual Studio build problems

### ISSUE THREAD

**Issue by mattparks** [AndreRenaud/PDFGen#28]
I'm using PDFGen in a C++ project in Visual Studio 2019, when I try to compile I get a few compile errors:

- `#include <strings.h>` cannot be found
- `#define _XOPEN_SOURCE` will not define M_SQRT2, `#define _USE_MATH_DEFINES` will
- `SKIP_ATTRIBUTE` is not defined, when `_MSC_VER < 1900` is removed I have no problem
- `stat` is not a valid symbol, I can use `#define stat _stat` in the MSC_VER block

**Comment by AndreRenaud** [comment]
Hi Matt,
I've had a go at enabling appveyor & a windows build. Can you try the msvc-build branch and see if that works any better?
https://github.com/AndreRenaud/PDFGen/tree/msvc-build

**Comment by mattparks** [comment]
Visual Studio thinks this line has errors:
https://github.com/AndreRenaud/PDFGen/blob/939209821f7ef48955143d26ffe81acd3f74c836/pdfgen.c#L2112
But from what I can tell everything is liking correctly.

**Comment by AndreRenaud** [comment]
I just realised I was doing it on VS 2017. I'll try it on 2019 and get back to you.

**Comment by AndreRenaud** [comment]
I couldn't replicate that on 2019, but I've added in a workaround anyway. It should be good to go now.
