### ISSUE TITLE
Adding grayscale jpeg doesn't work

### ISSUE THREAD

**Issue by bghgary** [AndreRenaud/PDFGen#41]
Using the `pdf_add_jpeg` function works for RGB jpegs, but not for grayscale jpegs.

The reason is that `ColorSpace /DeviceRGB` needs to be `ColorSpace /DeviceGray` for grayscale images.

_I unfortunately don't know how to check for this in a JPEG file or I would have opened a PR :)_

**Comment by AndreRenaud** [comment]
Can you attach a reference to an image that is known to NOT work? I'll see what I can do.

**Comment by bghgary** [comment]
Here is one that doesn't work with DeviceRGB but works with DeviceGray. The jpg is written with [opencv](https://github.com/opencv/opencv). I've already included the pdf that works using DeviceGray.

> [test.zip](https://github.com/AndreRenaud/PDFGen/files/4304632/test.zip)

I noticed if I create a jpeg using Gimp with this `Test` image, the `jpeg_size` function was unable to determine the width and height. I'm not sure how robust this function is (the referenced link in the code http://www.64lines.com/jpeg-width-height doesn't work).  Perhaps if there is an function where the width, height, color space is passed in? I already know the width, height, and color space.

**Comment by AndreRenaud** [comment]
Can you check out https://github.com/AndreRenaud/PDFGen/pull/42 and see if it solves things for you?

**Comment by bghgary** [comment]
Works perfect. Thanks for the fix!

**Comment by AndreRenaud** [comment]
Thanks for checking - I've merged the PR back into master. Let me know if you still see any problems.
