### ISSUE TITLE
Get image dimensions in library?

### ISSUE THREAD

**Issue by kojicomics** [AndreRenaud/PDFGen#5]
Hi,

First I want to thank you for work in this library :)
I'm currently working on a html2pdf converter in ANSI-C, and when it comes to drawing an img without dimensions, I needed to create a function to get its original height and width.

Since to draw an image with PDFGen the dimensions are mandatory, do you think it would be useful to include that function in the library or would you prefer it to be a feature to be implemented in the client?

If you want, I can send a pull request implementing this feature.

**Comment by AndreRenaud** [comment]
Hi,
The dimensions that you specify when adding an image are not the pixel dimensions of the image, they're the displayed width/height of the image when it is rendered in the PDF, specified in points. So they don't really have anything to do with how large the image itself it. Extracting dimensions from the image seems like something that should be done outside of PDFGen.

**Comment by kojicomics** [comment]
Perfect, thanks
