### ISSUE TITLE
Feature Request: Simple Form Fields.

### ISSUE THREAD

**Issue by burningreggae** [AndreRenaud/PDFGen#54]
Dear Andre Renaud!.

Would it be easy to enhance pdfgen with some simple PDF Form Fields Checkbox etc ?

Thanks
burning

**Comment by AndreRenaud** [comment]
I've had a quick look, and PDF forms don't seem terrible. But I don't think I'm going to have time to look at this myself any time soon.
There is a reference PDF from Adobe at https://www.adobe.com/technology/pdfs/presentations/KingPDFTutorial.pdf which has a good example of these, if you have time to take a look.

**Comment by burningreggae** [comment]
Thanks!. 
Thanks for answering and the kingpdf tutorial! (you can close this comment;-) )

I just wanted to say i like your single c-file solution very much!
But for sure this comes with the burden to understand your list/flexarray catalog implementation;-)

I didn't fork you code, i just took the plain c file and already started to make minor modifications.
May I send you some small hint's ? (no pull request..).
```
static inline int flexarray_get_bin_size(const struct flexarray *flex,int bin)
{
    if (bin >= ARRAY_SIZE(bin_offset))
        return -1;
    int next = bin_offset[bin + 1];
}
```
the compare could be one off, because you accessing later [bin+1].
So it should be smth like
```
if (bin >= ARRAY_SIZE(bin_offset)-1)
        return -1;
```
 
some  c-compilers (not c99?) also complain about variable-declarations inside the for-scope.
```
    for (int i = 0; i < ARRAY_SIZE(bin_offset); i++)
```
should be everywhere
```
	int i;
	for (i = 0; i < ARRAY_SIZE(bin_offset); i++)
```
but that's maybe because i do not use your make files.. [directly static compile].

Thanks!
burning

**Comment by AndreRenaud** [comment]
Thanks for the note regarding the flex arrays. That was a bug.
For the C99, I've decided that C99 is the minimum supported level, so I'm going to retain that syntax for now. Hopefully that isn't too much of a problem.
