### ISSUE TITLE
Blank Pages

### ISSUE THREAD

**Issue by miltonneal54** [AndreRenaud/PDFGen#55]
Hi Andre
I downloaded PDFGen project and compiled (using VS2013) it with you test main.c
All compiled without issue and it generates a pdf file when run.
Only when viewed with Acrobat Reader DC I get 3 blank A4 pages and 1 black A3 page along this the bookmarks.
I downloaded Soda PDF and it displays the pages correctly.
Do you know of any reason why 
PDFGen doesn't generate Adobe compatible pdf's.
Thanks in advance... Milton
![Adobe](https://user-images.githubusercontent.com/65113973/82729780-d1ab2e80-9d2c-11ea-88d9-d172cfecc616.PNG)

**Comment by AndreRenaud** [comment]
Do you mean the output.pdf from the test program doesn't display properly? That is strange, it works fine here in Acroread. Can you send me the output.pdf that you're generating? Perhaps something has happened to it.

**Comment by miltonneal54** [comment]
Hi Andre
This is the output.pdf produced.
I even tried sending it to my phone and open it with the Acrobat app, but get the same result. Blank pages.
Let us know how you get on.
Thanks Milton
[output.pdf](https://github.com/AndreRenaud/PDFGen/files/4676520/output.pdf)

**Comment by AndreRenaud** [comment]
I've had a look at the output, and I think this is because the %zu printf specifier is not being recognised by your compiler. Can you tell me what compiler you used to generate this?

In your output I see things like:
```
<< /Length zu >>stream
```

But it should be:
```
<< /Length 137 >>stream
```

**Comment by miltonneal54** [comment]
Andre
You are correct, I changed line:
dstr_printf(&obj->stream, "<< /Length %zu >>stream\r\n", len);
to:
dstr_printf(&obj->stream, "<< /Length %u >>stream\r\n", (unsigned int)len);
and this works fine, generating a pdf that is read correctly by Adobe.
I'm not sure what version of C/C++ compiler VS2013 used but obviously earlier than C99 specification.
Thanks for bring this to light.
Milton

**Comment by AndreRenaud** [comment]
I'm basically assuming C99 compatible compiler in the code, so I'll close this issue. Feel free to reopen if you think there is a better solution.
