### ISSUE TITLE
Alignment of rendered text

### ISSUE THREAD

**Issue by sumit809** [AndreRenaud/PDFGen#57]
Hi @AndreRenaud 
If I align the text as PDF_ALIGN_CENTER at the centre of the A4 page, the text still aligns as left. Also the left and right alignment is not working as I am hoping.

I'm assuming that if I write "ATA", the letter T should be at the xy co-ordinates.
Also, since it's not the word document, you can add 9 different alignment options as you can see in the attached image.
1. Top-left         2. Top-Center         3. Top-Right
4. Center-left   5. Center                 6. Center-Right
7. Bottom-left   8. Bottom-Center  9. Bottom-Right

![Screenshot 2020-05-28 at 8 54 40 PM](https://user-images.githubusercontent.com/21221820/83161231-ce95b100-a125-11ea-80ad-58a2ac3eaf10.png)

**Comment by AndreRenaud** [comment]
The alignments are relative to the bounding box, not the x,y coordinate, so you typically make the bounding box as wide as the maximum available space, and centre it within there. At this stage there is no support for vertical alignment, mostly because I haven't had a need for it yet. If you have a suggested patch or PR, that would be welcome.

**Comment by sumit809** [comment]
Thanks for explaining that how it works. I don't have the patch for this right now. I will see if there is any or write one.

**Comment by sumit809** [comment]
Hi,
I created new function by modifying pdf_add_text_wrap function independent of wrap width which can help aligning text depending on the x-y co-ordinates.
Here I added two alignment options bottom-centre and bottom-right. and it's working...

`
int pdf_add_text_align(struct pdf_doc *pdf, struct pdf_object *page,
                      const char *text, float size, float xoff, float yoff,
                      uint32_t colour, int align, float *height)
{
    /* Move through the text string, stopping at word boundaries,
     * trying to find the longest text string we can fit in the given width
     */
    const char *start = text;
    const char *last_best = text;
    const char *end = text;
    char line[512];
    const uint16_t *widths;
    float orig_yoff = yoff;

    widths = find_font_widths(pdf->current_font->font.name);
    if (!widths)
        return pdf_set_err(pdf, -EINVAL,
                           "Unable to determine width for font '%s'",
                           pdf->current_font->font.name);

    while (start && *start) {
        const char *new_end = find_word_break(end + 1);
        float line_width;
        int output = 0;
        float xoff_align = xoff;
        int e;

        end = new_end;

        e = pdf_text_point_width(pdf, start, end - start, size, widths,
                                 &line_width);
        if (e < 0)
            return e;

        
        if (*end == '\0')
            output = 1;

        if (*end == '\n' || *end == '\r')
            output = 1;

        if (output) {
            int len = end - start;
            float char_spacing = 0;
            if (len >= sizeof(line))
                len = sizeof(line) - 1;
            strncpy(line, start, len);
            line[len] = '\0';

            e = pdf_text_point_width(pdf, start, len, size, widths,
                                     &line_width);
            if (e < 0)
                return e;

            switch (align) {
            case PDF_ALIGN_BOTTOM_RIGHT:
                xoff_align -= line_width;
                break;
            case PDF_ALIGN_BOTTOM_CENTER:
                xoff_align -= line_width / 2;
                break;
            }

            if (align != PDF_ALIGN_NO_WRITE) {
                pdf_add_text_spacing(pdf, page, line, size, xoff_align, yoff,
                                     colour, char_spacing);
            }

            if (*end == ' ')
                end++;

            start = last_best = end;
            yoff -= size;
        } else
            last_best = end;
    }

    if (height)
        *height = orig_yoff - yoff;
    return 0;
}`

I also wanted to implement other alignment options that I suggested in first comment, but I don't know how to use height. I tried using 

`case PDF_ALIGN_CENTER_CENTER: // for center alignment
                xoff_align -= line_width / 2;
                yoff -= height / 2;
                break;
`

but it throws error
`error: invalid operands to binary / (have ‘float *’ and ‘int’)
                 yoff -= height / 2;
                                ^`
Can you please suggest how can I use this? And can you please add the above implementation in your current code?

**Comment by AndreRenaud** [comment]
The reason that fails is that height is not known at the beginning - it is calculated based on the number of lines (that is why it's a pointer, not just a straight float). Because of the line-breaking calculation, it is not entirely trivial to do this for full paragraphs. You have to split it into two phases - firstly break it up into lines (or at least calculate how many lines), use that to determine the overall height, and then do it again so that you can vertically position each line properly.

**Comment by sumit809** [comment]
Since I'm not this good in C to deal with the pointers, I will Continue to use what you have developed🙈 
Also, any plans on adding "graph plotting" feature?😛

**Comment by AndreRenaud** [comment]
Sorry, graphing at this stage isn't something that I had thought much about.
