### ISSUE TITLE
PDF Size

### ISSUE THREAD

**Issue by sumit809** [AndreRenaud/PDFGen#58]
Hi Andre,

This issue was already raised by @nomancyclewala but closed due to its lack of need by users.

I will be generating at least 100 pages as shown in the attachment, but the size is increasing proportionally.

Is there anyway to reduce it?

[pdf2.pdf](https://github.com/AndreRenaud/PDFGen/files/4742099/pdf2.pdf)

[main.txt](https://github.com/AndreRenaud/PDFGen/files/4742108/main.txt)

**Comment by AndreRenaud** [comment]
Size isn't something that PDFGen really focuses on. It's more about simplicity. The only area that would be good to save size on is re-using the same image. At the moment it will be duplicated, but it could be done more efficiently. For your example, where it is just a lot of text, there aren't any really easy wins I'm afraid.

**Comment by sumit809** [comment]
Okay!
