### ISSUE TITLE
<sys/stat.h> no such file or directory found

### ISSUE THREAD

**Issue by sumit809** [AndreRenaud/PDFGen#59]
Hi Andre,

I'm trying to port this library in MPLAB X IDE and the compiler is XC32 ver2.41. 
After adding pdfgen.c and pdfgen.h in my project I'm facing several issues in which this 
`<sys/stat.h> no such file or directory found` is the one which I can't get over with. The compiler has all required header files except this. I found such header in Arduino Directory and tried to copy them in my project but it only added with more errors.

How can this be solved?

**Comment by AndreRenaud** [comment]
You can comment that line out, but that means you will not be able to have the `pdf_add_raw_jpeg` function, so you will want to comment that function out as well (and `pdf_add_jpeg` which call it). So you won't be able to add JPEG files from the filesystem, but if you're missing sys/stat.h, you probably don't have a filesystem anyway.

**Comment by sumit809** [comment]
Okay! Thank You!
