### ISSUE TITLE
TrustInSoft follow up: formal verification of your test suite

### ISSUE THREAD

**Issue by jakub-zwolakowski** [AndreRenaud/PDFGen#60]
Hi Andre,

Let me know if you had a chance to take a look at the continuous integration tool TrustInSoft CI.

I began to set it up on this project. Here’s the link: https://ci.trust-in-soft.com/projects/jakub-zwolakowski/PDFGen/1

On the 2 test cases which I configured, no Undefined Behaviors were encountered, as you have already fixed all the issues that we had found before.

You can also see how it looks like when some more tests are added and different architectures checked: https://ci.trust-in-soft.com/projects/jakub-zwolakowski/PDFGen-UB/11

If you’re interested, I’m happy to help you with the setup. But also you shouldn't need much help: it involves creating an account, adding the `tis.config` file, and then some other minor configuration effort.

**Comment by AndreRenaud** [comment]
This has sat around for a while and I never got around to actioning it. Sorry about that. I'm assuming that this has moved on now (those links no longer work), so I'll close this issue. Thanks for your help with this.
