### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by MatthMoestl** [AndreRenaud/PDFGen#72]
It would be great , if we can use HDC -functions too

(like DrawText, LineTo, ...)

great work btw :-) thanks a lot !

**Comment by AndreRenaud** [comment]
Hi. Unfortunately most of those functions require some form of bounding box support, which PDFGen doesn't have right now. I'll keep it in mind, but I'm probably not going to work on it myself anytime soon.
Feel free to submit a PR though 😄

**Comment by MatthMoestl** [comment]
ok thanks,
I was using lightPDF before, and I switched to yours cause it looks much faster ^^
For now, I didn't find out how to catch DrawText commands, probably with commands like 
    CreateEnhMetaFile(NULL, NULL, &page_rect, NULL);
thanks




    On Monday, December 7, 2020, 10:47:59 PM GMT+1, Andre Renaud <notifications@github.com> wrote:  
 
 


Hi. Unfortunately most of those functions require some form of bounding box support, which PDFGen doesn't have right now. I'll keep it in mind, but I'm probably not going to work on it myself anytime soon.
Feel free to submit a PR though 😄

**Comment by AndreRenaud** [comment]
I'm going to close this issue, since I don't think we're going to re-work the API in that way. Please re-open if there is anything new to discuss.
