### ISSUE TITLE
Add support for UPC barcodes

### ISSUE THREAD

**Issue by AndreRenaud** [AndreRenaud/PDFGen#81]
https://en.wikipedia.org/wiki/Universal_Product_Code

Should add a new function `pdf_add_barcode_upc`, to be called from `pdf_add_barcode`, and a new barcode enum, PDF_BARCODE_UPC

**Comment by mcgouganp** [comment]
Hi. I have a branch with this done for EAN-13, EAN-8, UPC-A and UPC-E barcodes, but I'm having trouble with the automated testing. Should I just create a pull request for you to look at it, or do you want to just look at it in my repo?

**Comment by AndreRenaud** [comment]
Sure, just open a pull request and we can look at it there. The automated testing on this repo is pretty aggressive, so I don't mind sorting that side out.

**Comment by AndreRenaud** [comment]
Given the state of things, I'll probably close this issue now. There's definitely more barcodes that could be supported, but it hardly seems like a pressing issue anymore.
