### ISSUE TITLE
Issues with adding png image files to pdf

### ISSUE THREAD

**Issue by JohnGreek** [AndreRenaud/PDFGen#82]
Hello. 
First of all, great work on the library, it is very helpful.

Now, my issue is that when i attempt to add a .png image either from memory or from file to a newly created pdf file:

1. If the image DOES contain alpha channel and i read it from file, the error "PDF doesn't support PNG alpha channel" is displayed
2. If the image DOES contain alpha channel and i read it from memory, the error "PNG chunk length larger than file"  is displayed
3. If the image does NOT contain alpha channel and i read it from file, the error "PNG chunk length larger than file" is displayed
4. If the image does NOT contain alpha channel and i read it from memory, the error "PNG chunk length larger than file" is displayed

I dug in the source and this line:
`chunk = (const struct png_chunk *)&png_data[pos];`

does not seem to read correctly the chunk length.
The number i debug as chunk length inside the source (right after that line) is 218103808 instead of 13. This happens on the first iteration of the while(1) loop, while reading the "IHDR" length bytes. 

Tried with more than one image, the same number is returned. 
Tried to set chunk->length by reading manually 4 bytes from png_data, but it fails after some iterations with error "Wrong PNG format, chunks not found".

The images used to test the issue were downloaded from the internet, they are displayed correctly in programs(windows Photo, gimp etc.), and are not changed in any way from my program, just loaded as bytes.
Note that i have tested the validity of those loaded bytes by saving them to a test file, which is a perfectly working file. So the bytes are likely not corrupt/messed in any way.

**Comment by AndreRenaud** [comment]
Hi. Thanks for this report. The PNG support was only recently added, and does currently only support a limited range of PNG images types. Are you able to attach some known to be broken PNG images to this bug report, and I'll look into it?

**Comment by JohnGreek** [comment]
Sure, i drag & drop them here, or paste a link?

> Note that the PNG chunks have their length encoded as big endian, so if you're on a little endian machine (x86/ARM), they won't immediately decode in the debugger. That's what the ntoh32 function is for.
Nope, just a regular win 10 machine

**Comment by AndreRenaud** [comment]
I think a link would be simplest, I'm not sure you can actually host files on GitHub bug reports.

**Comment by JohnGreek** [comment]
Very well, here are the links:
https://imgur.com/QZfYbkE
https://imgur.com/PwhYknP

I can test things if you need extra help, just tell me if you need something to look into

**Comment by AndreRenaud** [comment]
Hi John. I've got a partial fix that resolves an issue with PNG files that were split over multiple chunks (this is pretty common on larger files. We'd only tested with tiny files).
The alpha support issue is a bit harder though, as it is not natively supported by PDF.
Can you test the version here and confirm if it resolves some of the issues for you?
https://github.com/AndreRenaud/PDFGen/tree/png-chunkgs

**Comment by JohnGreek** [comment]
Thank you very much, i will test it and get back to you

**Comment by JohnGreek** [comment]
> Can you test the version here and confirm if it resolves some of the issues for you?

I run the same tests(1-4) with the new branch and i face the exact same issues (ignore the alpha channel points, i just run all of them again to get the updated state after applying the fix). The chunk size is still 218103808.<br><br>
May i point something, 
https://github.com/AndreRenaud/PDFGen/blob/png-chunkgs/pdfgen.c#L2516

Looking through the code and searching online, i run into this: https://stackoverflow.com/questions/19995440/c-cast-byte-array-to-struct
```c
typedef struct
{
    uint32_t id;
    uint16_t test;
    uint8_t group;
    uint32_t time;
}
```
>The compiler will probably place padding between "group" and "time" to ensure that "time" is on a 4-byte boundary


Note, i'm not really familiar with C, but, If understand correctly, this happens if the data types are mixed in regards to byte size. So, the struct "png_chunk" is 8 bytes (length : 4 bytes, type : 4 bytes), so it shouldn't have this issue(?), but when i manually set the "length" property like this (naive way to test it)
```c++
chunk->length = ( png_data[pos] | png_data[pos + 1] | png_data[pos + 2] | png_data[pos + 3] );
```
the "length" value was correct, at least for the "IHDR" chunk, but failing later (as mentioned in my first post)<br><br>


> The alpha support issue is a bit harder though, as it is not natively supported by PDF.

I totally understand

**Comment by AndreRenaud** [comment]
Yes, there was an issue with packed structs. Hopefully this is fixed now. The length issue is what the ntoh32 is designed to resolve, so this shouldn't be a problem. Can you have a look at the latest code on that branch and tell me if it resolves your issue?

**Comment by AndreRenaud** [comment]
The alpha support on PNGs is unlikely to ever be supported. This is mostly because of the amount of code it would require, and PDFGen is designed to be pretty small. I'll close this for now, but feel free to reopen if there are any other outstanding issues.
