### ISSUE TITLE
MINGW COMPILATION

### ISSUE THREAD

**Issue by moseswis** [AndreRenaud/PDFGen#87]
how do i get it to run on windows codeblocks...
undefined reference to `pdf_create'

**Comment by AndreRenaud** [comment]
It looks like you haven't included pdfgen.c into the project, or it isn't getting compiled in. Are there any more details you can provide?

**Comment by moseswis** [comment]
thanks for replying...im still learning..im using codeblocks on windows 10.

**Comment by moseswis** [comment]
ICT\Desktop\dev cpp\pdfgen\pdfgen.c|253|warning: declaration does not
declare anything|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c||In function 'pdf_object_destroy':|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|614|error: 'struct pdf_object' has no
member named 'stream'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|617|error: 'struct pdf_object' has no
member named 'page'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|620|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|623|error: 'struct pdf_object' has no
member named 'bookmark'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c||In function 'pdf_create':|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|699|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|699|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|700|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|705|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|706|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|706|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|707|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|707|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|708|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|708|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|709|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|709|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|710|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|710|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|711|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|711|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|714|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|724|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|724|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|727|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|728|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|728|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|729|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|730|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|730|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|731|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|732|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|732|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|733|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|734|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|734|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|735|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|736|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|736|error: 'struct pdf_object' has no
member named 'info'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c||In function 'pdf_set_font':|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|794|error: 'struct pdf_object' has no
member named 'font'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|796|error: 'struct pdf_object' has no
member named 'font'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|804|error: 'struct pdf_object' has no
member named 'font'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|804|error: 'struct pdf_object' has no
member named 'font'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|805|error: 'struct pdf_object' has no
member named 'font'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|805|error: 'struct pdf_object' has no
member named 'font'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|806|error: 'struct pdf_object' has no
member named 'font'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c||In function 'pdf_append_page':|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|823|error: 'struct pdf_object' has no
member named 'page'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|824|error: 'struct pdf_object' has no
member named 'page'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c||In function 'pdf_page_set_size':|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|837|error: 'struct pdf_object' has no
member named 'page'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|838|error: 'struct pdf_object' has no
member named 'page'|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c||In function 'pdf_save_object':|
 ICT\Desktop\dev cpp\pdfgen\pdfgen.c|858|error: 'struct pdf_object' has no
member named 'stream'|
||More errors follow but not being shown.|
||Edit the max errors limit in compiler options...|
||=== Build finished: 50 errors, 1 warnings (0 minutes, 0 seconds) ===|

**Comment by AndreRenaud** [comment]
It looks like your compiler doesn't support anonymous structs
Can you tell me what compiler you're using? It's possible you can pass it some compile flag to enable this feature.

**Comment by AndreRenaud** [comment]
According to some quick Googling, adding `-fms-extensions` to your CFLAGS might be the answer.
https://youtrack.jetbrains.com/issue/CPP-21841

**Comment by moseswis** [comment]
codeblocks gcc compiler

**Comment by AndreRenaud** [comment]
I'm going to close this issue - it looks like you got it going.
