### ISSUE TITLE
Adding an image as the entire page

### ISSUE THREAD

**Issue by JulianGmp** [AndreRenaud/PDFGen#95]
Hello,

First of all, thank you for the work on this library. I am amazed that this runs without any external dependencies.

I'm trying to convert a large collection of images to a PDF, and have each image be its own page while keeping aspect ratio and image quality.

The problem here is that I need know the image size before calling `pdf_page_set_size`.
I have read through issue #5, and I understand your reasoning not to include a „get image size“ function.
However, since you do read the image headers and parse the image dimensions when adding the image anyway, it is easy to achieve what I described above. While testing I simply changed `pdf_add_png_data`'s last few lines:
```c
pdf_page_set_size(pdf, page, info.width, info.height);
return pdf_add_image(pdf, page, obj, x, y, info.width, info.height);
```

Do you think it would be feasable to have a function seperate from `pdf_add_image_file`/`pdf_add_image_data` (or a parameter) to achieve this?

I know this is a rather special use case, but I think this would be the better solution rather than to pull some huge dependency only to determine the image dimensions.
If I find time in the coming days I will work on a patch that introduces something like this - if I can manage to make it not horrible.

**Comment by AndreRenaud** [comment]
Hi Julian,
The tricky thing is that info.width is pixels, but set_size is in points (1/72nd of an inch).
Are you trying to make it such that the individual pages of the PDF are each entirely filled with the image (ie: no border, and the PDF pages don't really line up with a physical paper size, like A4 or US-Letter)?
If that's the case, then I agree it's a bit difficult at the moment. But in general the idea has been that the resultant PDF is normally designed for printing, and so should line up with some kind of physical paper size. If you just want the image to be as large as possible, while still fitting on the paper size (and presumably maintaining the aspect ratio), then I think a better thing to do would be to extent the various image functions to allow them to autocalculate the width (or height), such that it maintains aspect ratio.

**Comment by JulianGmp** [comment]
> Are you trying to make it such that the individual pages of the PDF are each entirely filled with the image (ie: no border, and the PDF pages don't really line up with a physical paper size, like A4 or US-Letter)?

Yes exactly, I know it's rather.. crude and very much an edge case that not many people have.

I do see the benefit of what you described as well, being able to adjust the image dimensions to the page size while retaining aspect ratio should be doable without changing the function signature.

The case I have is a bit special, because I need to modify the page after parsing the image data, but just before adding the image data.

I'll look into creating those features the next few days.

**Comment by JulianGmp** [comment]
I just implemented the resizing while respecting aspect ratio issue that you mentioned.

I also thought about my use case again and I have a suggestion for a feature that would cover my case but might also be useful for others: a flag that (if set) will expand a pages size if the placed image goes outside the page.
We can easily calculate this with the given x and y positions, the display dimensions and the page size.

In my case I would resize the page to a 1x1 before adding the image and I would automatically get a page that is the exact size of my image.

The other alternative that I thought of would be to define a struct for basic image info, similar to `png_info`.
That way I could read the file in manually, get the image dimensions, resize the page and call `pdf_add_image_data`.

**Comment by AndreRenaud** [comment]
With the merge of #105 this should be possible now?

**Comment by JulianGmp** [comment]
Yes, you can grab an image's size with the newly added `pdf_parse_image_header` and use that to set the page size.
