### ISSUE TITLE
l can't find data_penguin_jpg[] and data_penguin_jpg_len 

### ISSUE THREAD

**Issue by 7889zcm** [AndreRenaud/PDFGen#97]
extern unsigned char data_penguin_jpg[] in main.c 
But  l can't find it in other.c
?

**Comment by AndreRenaud** [comment]
Hi. The penguin C code is automatically generated from the data/penguin.jpg file. If you look in the Makefile, you'll see there is a rule involving xxd to convert the .jpg data into a C array so we can access it in code.
